services:
  - type: web
    name: manim-api
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: "echo Starting from Dockerfile"
    plan: free
    envVars:
      - key: AWS_ACCESS_KEY_ID
        value: your-access-key
      - key: AWS_SECRET_ACCESS_KEY
        value: your-secret-key
      - key: AWS_REGION
        value: ap-south-1
      - key: S3_BUCKET_NAME
        value: your-bucket
